### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by ghost** [huanghongxun/WaterPower#37]
Hi,

in version 0.4.2 I get the following exception (forge server: 1.10.2-12.18.2.2105):

[17:54:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at waterpower.common.block.reservoir.ReservoirType.getShowedName(ReservoirType.java:33) ~[ReservoirType.class:?]
        at waterpower.common.block.reservoir.ItemReservoir.func_77653_i(ItemReservoir.java:29) ~[ItemReservoir.class:?]
        at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:507) ~[adz.class:?]
        at net.minecraft.item.ItemStack.func_151000_E(ItemStack.java:956) ~[adz.class:?]
        at net.minecraft.stats.StatList.func_151181_c(StatList.java:181) ~[nw.class:?]
        at net.minecraft.stats.StatList.reinit(StatList.java:342) ~[nw.class:?]
        at net.minecraftforge.common.ForgeModContainer.mappingChanged(ForgeModContainer.java:471) ~[forge-1.10.2-12.18.2.2105-universal.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.10.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.10.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217) ~[LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.fireRemapEvent(Loader.java:1049) ~[Loader.class:?]
        at net.minecraftforge.fml.common.registry.PersistentRegistryManager.injectSnapshot(PersistentRegistryManager.java:357) ~[PersistentRegistryManager.class:?]
        at net.minecraftforge.fml.common.FMLContainer.readData(FMLContainer.java:327) ~[FMLContainer.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:418) ~[FMLCommonHandler.class:?]
        at net.minecraft.world.storage.SaveFormatOld.loadAndFix(SaveFormatOld.java:118) ~[azz.class:?]
        at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:121) ~[azy.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:224) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
        ... 28 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
        ... 28 more

**Comment by huanghongxun** [comment]
I'm grateful to you for reporting crashes again and again.
