### ISSUE TITLE
Crash with latest version 1.10.2-0.5.5

### ISSUE THREAD

**Issue by Spirevipp** [huanghongxun/WaterPower#46]
It seems like you have an extra space in a recipe.
Doesnt seem like github want to show the extra space, so just as you know its between the first GW and G

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WaterPower (waterpower)
Caused by: java.lang.RuntimeException: Invalid shaped ore recipe: GW,  G, GW, G, null, W, plankWood, 1xitem.waterpower.component@5
    at net.minecraftforge.oredict.ShapedOreRecipe.<init>(ShapedOreRecipe.java:135)
    at waterpower.common.recipe.Recipes.craft(Recipes.kt:83)
    at waterpower.common.item.ItemComponent$Companion.postInit(ItemComponent.kt:118)
    at waterpower.common.item.ItemComponent.postInit(ItemComponent.kt)

**Comment by huanghongxun** [comment]
Thanks for your reporting this issue.
Fixed in 0.5.6.
