### ISSUE TITLE
Crash during MC Launch - java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path

### ISSUE THREAD

**Issue by sab0tic** [huanghongxun/WaterPower#50]
This happens on every launch with WaterPower enabled - I have tried all of the latest versions and unfortunately this occurs with all of them. below is the crash report! I hope this helps...very excited to try your mod, looks like you have put alot of hard work into it, but am currently unable to try it due to this crash.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  ForgelinPlugin (Forgelin-1.5.1.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.11.16-universal.jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  MDECore-Core (mdecore-1.10.2-1.5.1.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.1.21.jar)
  IC2core (industrialcraft-2-2.6.252-ex110.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  MalisisSwitchesPlugin (malisisswitches-1.10.2-3.2.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta3-anarchy.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.9.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  HammerCoreCore (HammerCore_1.10.2-1.6.9.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 8/20/17 12:17 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WaterPower (waterpower)
Caused by: java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 68: file:/C:/Users/sab0t/Documents/Curse/Minecraft/Instances/BEASTFEEDER 3 (1)/mods/WaterPower-1.10.2-0.5.8.jar
	at com.google.common.reflect.ClassPath.getClassPathEntries(ClassPath.java:293)
	at com.google.common.reflect.ClassPath.from(ClassPath.java:91)
	at waterpower.annotations.ClassEngine.findClassesInURL(ClassEngine.kt:116)
	at waterpower.annotations.AnnotationSystem.initialize(AnnotationSystem.kt:37)
	at waterpower.WaterPower.onConstruction(WaterPower.kt:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:559)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:220)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.net.URISyntaxException: Illegal character in path at index 68: file:/C:/Users/sab0t/Documents/Curse/Minecraft/Instances/BEASTFEEDER 3 (1)/mods/WaterPower-1.10.2-0.5.8.jar
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:939)
	at com.google.common.reflect.ClassPath.getClassPathEntries(ClassPath.java:291)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 844886568 bytes (805 MB) / 1744306176 bytes (1663 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2316 162 mods loaded, 161 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
	UC	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
	UC	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UC	OpenComputers|Core{1.6.2.7} [OpenComputers (Core)] (minecraft.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UC	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UC	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UC	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.10.2-1.0.7.jar) 
	UC	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UC	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.7.jar) 
	UC	mdecore{1.10.2-1.5.1} [MattDahEpic Core] (mdecore-1.10.2-1.5.1.jar) 
	UC	autooredictconv{1.10.2-1.1.2} [Auto Ore Dictionary Converter] (autooredictconv-1.10.2-1.1.2.jar) 
	UC	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UC	basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
	UC	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UC	BaublesHud{3.2.0} [Baubles-Hud] (BaublesHud-1.10.2-3.2.0.jar) 
	UC	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UC	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	UC	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
	UC	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UC	BiomesOPlenty{5.0.0.2290} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2290-universal.jar) 
	UC	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
	UC	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UC	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UC	mcmultipart{1.3.0_87} [MCMultiPart] (MCMultiPart-experimental-2.0.0_88-universal.jar) 
	UC	CharsetLib{0.3.0-pre15} [‽] (Charset-0.3.0-pre15.jar) 
	UC	CharsetAudio{0.3.0-pre15} [♫] (Charset-0.3.0-pre15.jar) 
	UC	CharsetCarts{0.3.0-pre15} [U] (Charset-0.3.0-pre15.jar) 
	UC	CharsetDecoration{0.3.0-pre15} [⚿] (Charset-0.3.0-pre15.jar) 
	UC	CharsetDrama{0.3.0-pre15} [!] (Charset-0.3.0-pre15.jar) 
	UC	CharsetFarming{0.3.0-pre15} [;] (Charset-0.3.0-pre15.jar) 
	UC	CharsetGates{0.3.0-pre15} [&] (Charset-0.3.0-pre15.jar) 
	UC	CharsetPipes{0.3.0-pre15} [|] (Charset-0.3.0-pre15.jar) 
	UC	CharsetStorage{0.3.0-pre15} [#] (Charset-0.3.0-pre15.jar) 
	UC	CharsetTweaks{0.3.0-pre15} [*] (Charset-0.3.0-pre15.jar) 
	UC	CharsetWires{0.3.0-pre15} [+] (Charset-0.3.0-pre15.jar) 
	UC	CharsetWrench{0.3.0-pre15} [/] (Charset-0.3.0-pre15.jar) 
	UC	ChestTransporter{2.5.17} [Chest Transporter] (ChestTransporter-1.10.2-2.5.17.jar) 
	UC	chisel{MC1.10.2-0.0.13.29} [Chisel] (Chisel-MC1.10.2-0.0.13.29.jar) 
	UC	chiselsandbits{12.15} [Chisels & Bits] (chiselsandbits-12.15.jar) 
	UC	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UC	cofhcore{4.1.11} [CoFH Core] (CoFHCore-1.10.2-4.1.11.16-universal.jar) 
	UC	cookingforblockheads{4.2.45} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.45.jar) 
	UC	covers{0.4.1.17} [Simple Covers] (covers-0.4.1.17-mc1.10.2.jar) 
	UC	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.26.jar) 
	UC	MineTweaker3{3.0.26} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.26.jar) 
	UC	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.26.jar) 
	UC	ctm{MC1.10.2-0.2.1.21} [CTM] (CTM-MC1.10.2-0.2.1.21.jar) 
	UC	custommainmenu{2.0.5} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.5.jar) 
	UC	cyclopscore{0.10.7} [Cyclops Core] (CyclopsCore-1.9.4-0.10.7.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UC	darkutils{1.1.8.finalrc2} [Dark Utilities] (DarkUtilities-1.1.8.finalrc2.jar) 
	UC	DeathCounter{MC1.9.0v2} [DeathCounter] (DeathCounter-1.10.2-1.0.0.jar) 
	UC	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.5.1.jar) 
	UC	IC2{2.6.252-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.252-ex110.jar) 
	UC	forestry{5.2.17.383} [Forestry] (forestry_1.10.2-5.2.17.383.jar) 
	UC	eleccore{1.7.425} [ElecCore] (ElecCore-1.10.2-1.7.425.jar) 
	UC	OpenComputers{1.6.2.7} [OpenComputers] (OpenComputers-MC1.10.2-1.6.2.7.jar) 
	UC	deepresonance{1.4.8} [DeepResonance] (deepresonance-1.1x-1.4.8.jar) 
	UC	defaultoptions{6.1.5} [Default Options] (DefaultOptions_1.10.2-6.1.5.jar) 
	UC	poweradvantage{2.3.0} [Power Advantage] (PowerAdvantage_1.10.2-2.3.0.jar) 
	UC	electricadvantage{2.2.0} [Electric Advantage] (ElectricAdvantage_1.10.2-2.2.0.jar) 
	UC	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UC	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UC	EnderIO{1.10.2-3.1.193} [Ender IO] (EnderIO-1.10.2-3.1.193.jar) 
	UC	evilcraft{0.10.28} [EvilCraft] (EvilCraft-1.10.2-0.10.28.jar) 
	UC	zerocore{1.10.2-0.1.0.6} [Zero CORE] (zerocore-1.10.2-0.1.0.6.jar) 
	UC	bigreactors{1.10.2-0.4.5.30} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.30.jar) 
	UC	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UC	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UC	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-beta3-anarchy.jar) 
	UC	forgelin{1.5.1} [Shadowfacts' Forgelin] (Forgelin-1.5.1.jar) 
	UC	forgemultipartcbe{2.0.0.38} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UC	microblockcbe{2.0.0.38} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UC	minecraftmultipartcbe{2.0.0.38} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.38-universal.jar) 
	UC	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
	UC	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5.jar) 
	UC	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.10.2-alpha-0.0.3.jar) 
	UC	gendustry{1.6.5.31} [GenDustry] (gendustry-1.6.5.31-mc1.10.2.jar) 
	UC	googlyeyes{6.0.0} [GooglyEyes] (GooglyEyes-1.10.2-6.0.0.jar) 
	UC	gravestone{1.5.13} [Gravestone Mod] (gravestone-1.5.13.jar) 
	UC	hammercore{1.6.9} [Hammer Core] (HammerCore_1.10.2-1.6.9.jar) 
	UC	ichunutil{6.4.0} [iChunUtil] (iChunUtil-1.10.2-6.4.0.jar) 
	UC	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UC	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UC	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UC	immersivepetroleum{1.1.3} [Immersive Petroleum] (immersivepetroleum-1.10.2-1.1.3.jar) 
	UC	industrialwires{1.4-16} [Industrial Wires] (IndustrialWires-1.4-16.jar) 
	UC	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UC	ironbackpacks{1.10.2-2.2.29} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.29.jar) 
	UC	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
	UC	itank{1.1.0-1.10.2} [itank] (ITank-1.1.0-1.10.2.jar) 
	UC	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.10.2-0.11.0.jar) 
	UC	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.10.2.jar) 
	UC	journeymap{1.10.2-5.4.9b1} [JourneyMap] (journeymap-1.10.2-5.4.9b1.jar) 
	UC	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UC	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
	UC	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
	UC	malisisblocks{1.10.2-4.2.0} [Malisis Blocks] (malisisblocks-1.10.2-4.2.0.jar) 
	UC	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
	UC	malisisswitches{1.10.2-3.2.0} [Malisis Switches] (malisisswitches-1.10.2-3.2.0.jar) 
	UC	Mekanism{9.2.2} [Mekanism] (Mekanism-1.10.2-9.2.2.fix3.jar) 
	UC	MekanismGenerators{9.2.2} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.2.fix3.jar) 
	UC	MekanismTools{9.2.2} [MekanismTools] (MekanismTools-1.10.2-9.2.2.fix3.jar) 
	UC	natura{1.10.2-4.1.0.73} [Natura] (natura-1.10.2-4.1.0.73.jar) 
	UC	missing_pieces{4.3.0} [Missing Pieces] (missing_pieces-1.10.2-4.3.0.jar) 
	UC	ModNameTooltip{1.6.0} [Mod Name Tooltip] (modnametooltip_1.10.2-1.6.0.jar) 
	UC	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UC	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UC	MrTJPCoreMod{2.0.1.20} [MrTJPCore] (MrTJPCore-1.10.2-2.0.1.20-universal.jar) 
	UC	naturescompass{1.3.1} [Nature's Compass] (NaturesCompass-1.10.2-1.3.1.jar) 
	UC	netherportalfix{1.0} [Nether Portal Fix] (NetherPortalFix_1.10.2-3.3.4.jar) 
	UC	omlib{3.0.0-119} [OMLib] (omlib-1.10.2-3.0.0-119.jar) 
	UC	ompd{3.0.0-22} [Open Modular Passive Defense] (ompd-1.10.2-3.0.0-22.jar) 
	UC	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UC	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UC	shetiphiancore{3.3.9} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.9.jar) 
	UC	platforms{1.2.10} [Platforms] (platforms-1.10.0-1.2.10.jar) 
	UC	projectred-core{4.8.4.49} [ProjectRed Core] (ProjectRed-1.10.2-4.8.4.49-Base.jar) 
	UC	projectred-integration{4.8.4.49} [ProjectRed integration] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UC	projectred-transmission{4.8.4.49} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.4.49-integration.jar) 
	UC	projectred-fabrication{4.8.4.49} [ProjectRed Fabrication] (ProjectRed-1.10.2-4.8.4.49-fabrication.jar) 
	UC	projectred-illumination{4.8.4.49} [ProjectRed Illumination] (ProjectRed-1.10.2-4.8.4.49-lighting.jar) 
	UC	projectred-expansion{4.8.4.49} [ProjectRed Expansion] (ProjectRed-1.10.2-4.8.4.49-mechanical.jar) 
	UC	projectred-transportation{4.8.4.49} [ProjectRed Transportation] (ProjectRed-1.10.2-4.8.4.49-mechanical.jar) 
	UC	projectred-exploration{4.8.4.49} [ProjectRed Exploration] (ProjectRed-1.10.2-4.8.4.49-world.jar) 
	UC	railcraft{10.1.2} [Railcraft] (Railcraft_1.10.2-10.1.2.jar) 
	UC	reborncore{2.13.6.142} [RebornCore] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UC	reborncore-mcmultipart{2.13.6.142} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.6.142-universal.jar) 
	UC	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UC	refinedstorage{1.2.26} [Refined Storage] (refinedstorage-1.2.26.jar) 
	UC	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UC	roots{0.208} [Roots] (roots-0.208.jar) 
	UC	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UC	shearmadness{1.10.2} [Shear Madness] (shearmadness-1.10.2-1.7.0.4.jar) 
	UC	Signals{1.0} [Signals] (Signals-1.10.2-0.5.1-universal.jar) 
	UC	simplebarrels{1.26e} [Simple Barrels] (simplebarrels-1.26e.jar) 
	UC	valkyrielib{1.10.2-0.10.6} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.6.jar) 
	UC	simplegenerators{1.10.2-0.10.6a} [Simple Generators] (simplegenerators-1.10.2-0.10.6a.jar) 
	UC	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UC	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UC	solarfluxreborn{2.17r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-2.17r.jar) 
	UC	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	UC	steamadvantage{2.2.0} [Steam Advantage] (SteamAdvantage_1.10.2-2.2.0.jar) 
	UC	storagedrawersextra{1.10-1.1.0} [Storage Drawers Extras] (StorageDrawersExtras-1.10-1.1.0.jar) 
	UC	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UC	supercraftingframe{1.2.1.88} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.1.88.jar) 
	UC	tesla{1.2.1.49} [TESLA] (Tesla-1.10.2-1.2.1.49.jar) 
	UC	teslacoils{v0.2.1.0} [Tesla Coils] (teslacoils-0.2.3.0.jar) 
	UC	teslafied{1.0.0} [Teslafied] (teslafied-1.10.2-1.1.0.jar) 
	UC	thermalfoundation{2.1.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.5.12-universal.jar) 
	UC	thermalexpansion{5.1.9} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.9.23-universal.jar) 
	UC	thermaldynamics{2.0.10} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.10.16-universal.jar) 
	UC	wanionlib{1.10.2-1.3} [WanionLib] (WanionLib-1.10.2-1.3.jar) 
	UE	waterpower{@MODVERSION@} [WaterPower] (WaterPower-1.10.2-0.5.8.jar) 
	UC	worldstripper{1.3.0-1.10.2} [World Stripper] (World-Stripper-1.3.0-1.10.2.jar) 
	UC	yeoldetanks{2.0.2} [Ye Olde Tanks] (YeOldeTanks-1.10.2-2.0.2.jar) 
	UC	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	UC	unidict{1.10.2-2.9b} [UniDict] (UniDict-1.10.2-2.9b.jar) 
	UD	mdecore-core{1.0} [MDE Core - ASM Tweaks] (minecraft.jar) 
	Loaded coremods (and transformers): 
CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
ForgelinPlugin (Forgelin-1.5.1.jar)
  
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.11.16-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
MDECore-Core (mdecore-1.10.2-1.5.1.jar)
  com.mattdahepic.mdecore.asm.TickrateTransformer
CTMCorePlugin (CTM-MC1.10.2-0.2.1.21.jar)
  team.chisel.ctm.client.asm.CTMTransformer
IC2core (industrialcraft-2-2.6.252-ex110.jar)
  
TransformerLoader (OpenComputers-MC1.10.2-1.6.2.7.jar)
  li.cil.oc.common.asm.ClassTransformer
MalisisSwitchesPlugin (malisisswitches-1.10.2-3.2.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta3-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.9.jar)
  shetiphian.core.asm.ClassTransformer
Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
HammerCoreCore (HammerCore_1.10.2-1.6.9.jar)
  com.mrdimka.hammercore.asm.HammerCoreTransformer
RebornCoreASM (RebornCore-1.10.2-2.13.6.142-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.94' Renderer: 'GeForce GTX 780/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

**Comment by huanghongxun** [comment]
Please try to remove the white spaces and brackets in "BEASTFEEDER 3 (1)"

**Comment by sab0tic** [comment]
that appears to have worked! I will update our modpack name to BEASTFEEDER_3 from here on out to account for this, shouldn't be a problem. 

Thank you for the quick reply, and thanks for your hard work on this mod. very excited to try it out

**Comment by huanghongxun** [comment]
But actually I tried "BEASTFEEDER 3 (1)" in my computer and WaterPower works normally.
So this is still a problem waiting for a fix.
This issue remains open.

**Comment by scottosx** [comment]
I had this issue as well after duplicating my modpack with the Twitch launcher. It automatically appends the number, ie (1), to the name. So, this could be a problem which affects altered modpacks which choose to include your mod. I personally always duplicate a modpack before changing it.

Here is the log:
[crash-2017-10-21_15.30.35-client.txt](https://github.com/huanghongxun/WaterPower/files/1404433/crash-2017-10-21_15.30.35-client.txt)
